parameters:
    database_driver: pdo_mysql
    #database_host: 'http://serveur.zman-officiel.com'
    database_host: '127.0.0.1'
    database_port: 
    database_name: y-nov-labs
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 54423d9ed4813efdc643307598a849c9
    database_path: null
