photo:
    pattern:  /
    defaults: { _controller: "YnovLabsBundle:Photo:index" }

photo_show:
    pattern:  /{id}/show
    defaults: { _controller: "YnovLabsBundle:Photo:show" }

photo_new:
    pattern:  /new
    defaults: { _controller: "YnovLabsBundle:Photo:new" }

photo_create:
    pattern:  /create
    defaults: { _controller: "YnovLabsBundle:Photo:create" }
    requirements: { _method: post }

photo_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "YnovLabsBundle:Photo:edit" }

photo_update:
    pattern:  /{id}/update
    defaults: { _controller: "YnovLabsBundle:Photo:update" }
    requirements: { _method: post|put }

photo_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "YnovLabsBundle:Photo:delete" }
    #requirements: { _method: post|delete }
